# Generated by Django 3.1.5 on 2021-01-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20210116_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry',
            field=models.TextField(max_length=2500),
        ),
    ]
